# Generated by Django 5.2.1 on 2025-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_historicallisting_historicalrentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallisting',
            name='parking',
            field=models.CharField(blank=True, choices=[('', '無'), ('(含車位)', '含車位')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.CharField(blank=True, choices=[('', '無'), ('(含車位)', '含車位')], max_length=20),
        ),
    ]
