"""
Django settings for rent_house project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Add DLL directory to the search path (Windows only)
if os.name == 'nt':
    GDAL_LIBRARY_PATH = r'C:\OSGeo4W\bin\gdal311.dll'
    os.add_dll_directory(r"C:\OSGeo4W\bin")  # 確保這是正確的檔案路徑

# your_project/settings.py 你的Google_API_金鑰
MAPS_API_KEY = 'AIzaSyAfqVoO5g0Nwh4lhBNE-ppFDsMs4RX_0NM'

# Add DLL directory to the search path
# os.add_dll_directory("C:/OSGeo4W64/bin/")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-la-nz^+dd&u@fl$t#&7dc^#s215b)(!2485br2&0-@uv=4zev&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'listings.apps.ListingsConfig',
    'django.contrib.gis',  # 如果使用地理資訊系統功能
    'auditlog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rent_house.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Directory for custom templates
        # Ensure that the app directories are included for template discovery
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rent_house.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = { 
    'default': {
    'ENGINE': 'django.contrib.gis.db.backends.postgis',  # 使用 PostGIS 支援地理資訊系統
    # 'ENGINE': 'django.db.backends.mysql',
    'NAME': 'rent_house', 
    'USER': 'admin', 
    'PASSWORD': '123456',
    'HOST': 'localhost', 
    'PORT': '5432',  # PostgreSQL 的預設端口
    # 如果使用 MySQL，則取消以下註解並設定相關參數
    # 'OPTIONS': {
    #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES';",
    #     'charset': 'utf8mb4',
    # }
}}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# 當 Django 執行 collectstatic 時，會將所有靜態檔案收集到此目錄
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_collected') # 部署時用

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 新增以下設定
CRAWLER_SETTINGS = {
    'REGION': 1,  # 台北市
    'PER_PAGE': 30,
    'DEFAULT_PAGES': 2,
    'SLEEP_TIME': 1,
}

# settings.py
AUTH_USER_MODEL = 'listings.RentUser'

# 新增以下設定
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'rent_list'
LOGOUT_REDIRECT_URL = 'login'

#執行 collectstatic (部署時使用)
#python manage.py collectstatic

# 日誌設定
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'listings.admin': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# 設定後台頁面相關內容
ADMIN_SITE_HEADER = "租屋網站管理系統"
ADMIN_SITE_TITLE = "租屋網站管理"
ADMIN_INDEX_TITLE = "系統管理"